import { useCallback, useEffect, useState } from 'react';
import { CheckCircle2, ChevronRight, FileVideo, UploadCloud } from 'lucide-react';
import { listCourses, listLessons } from '../courses.api';
import LessonVideoUpload from '../components/LessonVideoUpload';

const UploadVideoPage = () => {
  const [courses, setCourses] = useState([]); const [lessons, setLessons] = useState([]); const [courseId, setCourseId] = useState(''); const [lessonId, setLessonId] = useState(''); const [loadingCourses, setLoadingCourses] = useState(true); const [loadingLessons, setLoadingLessons] = useState(false); const [error, setError] = useState('');
  const loadCourses = useCallback(async () => { setLoadingCourses(true); setError(''); try { const response = await listCourses({ manage: 'true' }); setCourses(response.data.data || []); } catch (err) { setError(err.response?.status === 403 ? 'You do not have permission to upload course content.' : 'Unable to load your courses.'); } finally { setLoadingCourses(false); } }, []);
  // Load the teacher's manageable courses when the dedicated upload page opens.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(() => { loadCourses(); }, [loadCourses]);
  const chooseCourse = async (value) => { setCourseId(value); setLessonId(''); setLessons([]); if (!value) return; setLoadingLessons(true); setError(''); try { const response = await listLessons(value); setLessons(response.data.data || []); } catch (err) { setError(err.response?.status === 403 ? 'You do not have permission to view these lessons.' : 'Unable to load lessons for this course.'); } finally { setLoadingLessons(false); } };
  const selectedCourse = courses.find((course) => course._id === courseId); const selectedLesson = lessons.find((lesson) => lesson._id === lessonId);
  const updateLesson = (updatedLesson) => setLessons((current) => current.map((lesson) => lesson._id === updatedLesson._id ? updatedLesson : lesson));
  return <main className="upload-video-page"><header className="upload-page-header"><div><p className="eyebrow">Content studio</p><h1>Upload Video</h1><p>Select a course and lesson, then add the video your learners will watch.</p></div><span className="upload-page-icon"><UploadCloud size={25} /></span></header>{error && <div className="dashboard-error" role="alert"><div><strong>Unable to continue</strong><p>{error}</p></div><button type="button" onClick={loadCourses}>Try Again</button></div>}<section className="upload-step-card"><div className="upload-step"><span>1</span><div><label htmlFor="upload-course">Course</label><p>Choose one of your courses.</p><select id="upload-course" value={courseId} onChange={(event) => chooseCourse(event.target.value)} disabled={loadingCourses}><option value="">{loadingCourses ? 'Loading courses…' : 'Select a course'}</option>{courses.map((course) => <option key={course._id} value={course._id}>{course.title}</option>)}</select></div></div><ChevronRight className="upload-step-arrow" size={21} /><div className={`upload-step ${!courseId ? 'disabled' : ''}`}><span>2</span><div><label htmlFor="upload-lesson">Lesson</label><p>{courseId ? 'Choose where to add the video.' : 'Select a course first.'}</p><select id="upload-lesson" value={lessonId} onChange={(event) => setLessonId(event.target.value)} disabled={!courseId || loadingLessons}><option value="">{loadingLessons ? 'Loading lessons…' : 'Select a lesson'}</option>{lessons.map((lesson) => <option key={lesson._id} value={lesson._id}>{lesson.order}. {lesson.title}</option>)}</select></div></div></section>{!courseId ? <section className="upload-empty"><span><FileVideo size={30} /></span><h2>Select a course to begin</h2><p>Choose a course above to load its lessons and upload lesson content.</p></section> : !lessons.length && !loadingLessons ? <section className="upload-empty"><span><FileVideo size={30} /></span><h2>No lessons in this course</h2><p>Add a lesson in My Content before uploading a video.</p></section> : selectedLesson ? <section className="upload-workspace"><div className="upload-workspace-header"><div><p className="eyebrow">Step 3</p><h2>{selectedLesson.title}</h2><p>{selectedCourse?.title}</p></div>{selectedLesson.videoUrl && <span className="video-ready"><CheckCircle2 size={16} /> Video uploaded</span>}</div><LessonVideoUpload courseId={courseId} lesson={selectedLesson} onUploaded={updateLesson} /></section> : <section className="upload-empty"><span><FileVideo size={30} /></span><h2>Select a lesson to continue</h2><p>Your upload controls will appear here.</p></section>}</main>;
};

export default UploadVideoPage;
