import { useCallback, useEffect, useState } from 'react';
import { getMyProfile, updateMyProfile } from './profile.api';

const ProfilePage = () => {
  const [data, setData] = useState(null); const [form, setForm] = useState({ name: '', phone: '', education: '', interests: '' }); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [message, setMessage] = useState('');
  const load = useCallback(async () => { setLoading(true); try { const response = await getMyProfile(); const next = response.data.data; setData(next); setForm({ name: next.user.name || '', phone: next.user.phone || '', education: next.profile?.education || '', interests: (next.profile?.interests || []).join(', '), bio: next.profile?.bio || '', expertise: (next.profile?.expertise || []).join(', '), qualifications: (next.profile?.qualifications || []).join(', '), instituteName: next.profile?.instituteName || '' }); } catch (error) { setMessage(error.response?.data?.message || 'Unable to load profile.'); } finally { setLoading(false); } }, []);
  useEffect(() => { load(); }, [load]);
  const save = async (event) => { event.preventDefault(); setSaving(true); setMessage(''); try { await updateMyProfile({ name: form.name, phone: form.phone, profile: { education: form.education, interests: form.interests.split(',').map((value) => value.trim()).filter(Boolean), bio: form.bio, expertise: form.expertise.split(',').map((value) => value.trim()).filter(Boolean), qualifications: form.qualifications.split(',').map((value) => value.trim()).filter(Boolean), instituteName: form.instituteName } }); setMessage('Profile updated successfully.'); await load(); } catch (error) { setMessage(error.response?.data?.message || 'Unable to update profile.'); } finally { setSaving(false); } };
  if (loading) return <main className="course-management-page"><p>Loading profile…</p></main>;
  return <main className="course-management-page"><header className="course-page-header"><div><p className="eyebrow">Account</p><h1>Profile</h1><p className="page-description">Manage your personal information and learning preferences.</p></div></header>{message && <div className="course-feedback" role="status">{message}</div>}<form className="course-form profile-form" onSubmit={save}><label>Name<input value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} required /></label><label>Email<input value={data?.user.email || ''} disabled /></label><label>Phone<input value={form.phone} onChange={(event) => setForm({ ...form, phone: event.target.value })} /></label><label>Education<input value={form.education} onChange={(event) => setForm({ ...form, education: event.target.value })} /></label>{data?.user.userType === 'student' && <label>Interests<span className="helper-text">Separate interests with commas.</span><input value={form.interests} onChange={(event) => setForm({ ...form, interests: event.target.value })} /></label>}{data?.user.userType === 'teacher' && <><label>Bio<textarea value={form.bio} onChange={(event) => setForm({ ...form, bio: event.target.value })} /></label><label>Expertise<span className="helper-text">Separate subjects with commas.</span><input value={form.expertise} onChange={(event) => setForm({ ...form, expertise: event.target.value })} /></label><label>Qualifications<span className="helper-text">Separate qualifications with commas.</span><input value={form.qualifications} onChange={(event) => setForm({ ...form, qualifications: event.target.value })} /></label></>}{data?.user.userType === 'coachingClassAdmin' && <label>Institute Name<input value={form.instituteName} onChange={(event) => setForm({ ...form, instituteName: event.target.value })} /></label>}<button className="primary-button" type="submit" disabled={saving}>{saving ? 'Saving…' : 'Save Profile'}</button></form></main>;
};

export default ProfilePage;
