import { useCallback, useEffect, useRef, useState } from 'react';
import { Bell } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { ignoreNotification, listNotifications, markAllNotificationsRead, markNotificationRead } from '../../features/notifications/notifications.api';
import './TopHeader.css';

const TopHeader = () => {
  const [notifications, setNotifications] = useState([]); const [showDropdown, setShowDropdown] = useState(false); const [loading, setLoading] = useState(false); const [error, setError] = useState('');
  const dropdownRef = useRef(null); const navigate = useNavigate();
  const fetchNotifications = useCallback(async () => { setLoading(true); setError(''); try { const response = await listNotifications(); setNotifications(response.data.data || []); } catch (requestError) { setError(requestError.response?.data?.message || 'Unable to load notifications.'); } finally { setLoading(false); } }, []);
  useEffect(() => { fetchNotifications(); const handleClickOutside = (event) => { if (dropdownRef.current && !dropdownRef.current.contains(event.target)) setShowDropdown(false); }; document.addEventListener('mousedown', handleClickOutside); return () => document.removeEventListener('mousedown', handleClickOutside); }, [fetchNotifications]);
  const handleAction = async (notification, action) => { try { if (action === 'ignore') await ignoreNotification(notification._id); else if (action === 'read') await markNotificationRead(notification._id); else if (action === 'renew' && notification.contractId?._id) { await markNotificationRead(notification._id); navigate('/contracts', { state: { renewContractId: notification.contractId._id } }); setShowDropdown(false); } await fetchNotifications(); } catch (requestError) { setError(requestError.response?.data?.message || 'Notification action failed.'); } };
  const markAll = async () => { try { await markAllNotificationsRead(); await fetchNotifications(); } catch (requestError) { setError(requestError.response?.data?.message || 'Unable to mark notifications read.'); } };
  const unreadCount = notifications.filter((notification) => !notification.isRead).length;
  const unreadLabel = unreadCount > 99 ? '99+' : String(unreadCount);
  return <div className="top-header"><div className="header-right"><div className="notification-bell-container" ref={dropdownRef}><button className="bell-button" type="button" aria-label="Notifications" onClick={() => setShowDropdown(!showDropdown)}><Bell size={20} />{unreadCount > 0 && <span className="notification-badge">{unreadLabel}</span>}</button>{showDropdown && <div className="notification-dropdown"><div className="dropdown-header"><h3>Notifications</h3>{unreadCount > 0 && <button type="button" onClick={markAll}>Mark all read</button>}</div><div className="dropdown-body">{loading ? <p className="no-notifications">Loading notifications…</p> : error ? <p className="no-notifications error-text">{error}</p> : !notifications.length ? <p className="no-notifications">No notifications yet.</p> : notifications.map((notification) => <div key={notification._id} className={`notification-item ${notification.isRead ? 'read' : 'unread'}`}><h4>{notification.title}</h4><p>{notification.message}</p>{!notification.isRead && <button className="btn-dismiss" type="button" onClick={() => handleAction(notification, 'read')}>Mark read</button>}{notification.type.startsWith('CONTRACT_EXPIRING') && notification.recipientRole === 'coachingClassAdmin' && <div className="notification-actions"><button className="btn-renew" type="button" onClick={() => handleAction(notification, 'renew')}>Renew Contract</button><button className="btn-ignore" type="button" onClick={() => handleAction(notification, 'ignore')}>Ignore</button></div>}</div>)}</div></div>}</div></div></div>;
};

export default TopHeader;
